version: 2.1
setup: true
orbs:
  # orb info: https://circleci.com/developer/orbs/orb/circleci/orb-tools
  # changelog: https://github.com/CircleCI-Public/orb-tools-orb/releases
  orb-tools: circleci/orb-tools@12.1.0

filters: &filters
  tags:
    only: /.*/

workflows:
  lint-pack:
    jobs:
      - orb-tools/pack:
          filters: *filters
      # Triggers the next workflow in the Orb Development Kit.
      - orb-tools/continue:
          pipeline_number: << pipeline.number >>
          vcs_type: << pipeline.project.type >>
          orb_name: checkout
          requires: [orb-tools/pack]
          filters: *filters
