version: 2.1
orbs:
  # changelog: https://github.com/CircleCI-Public/BATS-orb/releases
  bats: circleci/bats@1.1.0
  # orb under test
  checkout: {}
  # orb info: https://circleci.com/developer/orbs/orb/circleci/orb-tools
  # changelog: https://github.com/CircleCI-Public/orb-tools-orb/releases
  orb-tools: circleci/orb-tools@12.1.0

commands:
  test_clone_git_repo:
    parameters:
      # parameters copied from clone_git_repo
      debug:
        type: boolean
        default: false
        description: |
          When true, debug command logging is enabled
      depth:
        type: integer
        default: -1
        description: |
          Specifies the clone depth, indicating the number of recent commits to include.
          Default: -1 (fetches all commits).
      dest_dir:
        type: string
        default: ""
        description: |
          Destination directory for the repository.
          Defaults to DEST_DIR, then CIRCLE_WORKING_DIRECTORY, or current directory if unset.
      github_token:
        type: string
        default: ""
        description: |
          GitHub token. It can help to surpass connection quotas per machine.
      lfs:
        type: boolean
        default: false
        description:  |
          Enables cloning with Git Large File Storage (LFS) support.
      name_displayed:
        type: string
        default: "checkout/checkout"
        description: |
          The display name for the command.
#      repo_branch:
#        type: string
#        default: ""
#        description: |
#          Specifies the branch to checkout.
#          Defaults to REPO_BRANCH, then CIRCLE_BRANCH if unset.
#      repo_sha1:
#        type: string
#        default: ""
#        description: |
#          Specifies the commit SHA1 to checkout.
#          Defaults to REPO_SHA1, then CIRCLE_SHA1 if unset.
#      repo_tag:
#        type: string
#        default: ""
#        description: |
#          Specifies the tag to checkout.
#          Defaults to REPO_TAG, then CIRCLE_TAG if unset.
#      repo_url:
#        type: string
#        default: ""
#        description: |
#          Specifies the repository URL.
#          Defaults to REPO_URL, then CIRCLE_REPOSITORY_URL if unset.
      submodules:
        type: boolean
        default: false
        description: |
          Enables cloning of submodules.
      submodules_depth:
        type: integer
        default: -1
        description: |
          Specifies the clone depth for submodules, indicating the number of recent commits to include.
          Default: -1 (fetches all commits).
          # It is worth to remember that GitHub doesn't allow to fetch by SHA1.
          # In such a case, with shallow clone, the required reference can't be found.
          # https://github.com/boostorg/boost/issues/245#issuecomment-470716527
      # parameters specific only to test_clone_git_repo:
      repo_coordinates:
        type: string
        description: "Replacement for commented above"
      repo_url_template:
        type: string
        description: "Repo URL used with one string value for repo name."
        default: "https://github.com/rynkowsg/rynkowsg-orb-sample-repo-%s.git"
    steps:
      - run:
          name: Extract repo details
          command: |
            set -x
            IFS='|' read -r repo_name repo_branch repo_tag repo_sha1 < <(echo "<<parameters.repo_coordinates>>")
            echo "export REPO_URL=\"$(printf "<<parameters.repo_url_template>>" "${repo_name}")\"" >> $BASH_ENV
            echo "export REPO_BRANCH=$repo_branch" >> $BASH_ENV
            echo "export REPO_TAG=$repo_tag" >> $BASH_ENV
            echo "export REPO_SHA1=$repo_sha1" >> $BASH_ENV
      - checkout/checkout:
          debug: <<parameters.debug>>
          depth: <<parameters.depth>>
          dest_dir: <<parameters.dest_dir>>
          lfs: <<parameters.lfs>>
          name_displayed: <<parameters.name_displayed>>
          submodules: <<parameters.submodules>>
          submodules_depth: <<parameters.submodules_depth>>
      - run:
          name: "Run tests"
          environment:
            LFS_ENABLED: <<parameters.lfs>>
            SUBMODULES_ENABLED: <<parameters.submodules>>
            PARAM_DEST_DIR: <<parameters.dest_dir>>
          command: |
            # the DEST_DIR logic here maches logic from the checkout bash impl
            DEST_DIR=${PARAM_DEST_DIR:-${DEST_DIR:-${CIRCLE_WORKING_DIRECTORY:-.}}}
            eval DEST_DIR="${DEST_DIR}"
            ${DEST_DIR}/@bin/test.bash

docker_base_small: &docker_base_small
  docker: [{ image: "cimg/base:2023.12" }]
  resource_class: small

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test_clone_without_prior_checkout:
    <<: *docker_base_small
    parameters:
      repo_coordinates: {type: string}
      lfs: {type: boolean}
      submodules: {type: boolean}
    steps:
      - bats/install
      - test_clone_git_repo:
          debug: false
          repo_url_template: "https://github.com/rynkowsg/test-clone-repo-%s.git"
          repo_coordinates: << parameters.repo_coordinates >>
          lfs: << parameters.lfs >>
          submodules: << parameters.submodules >>
          dest_dir: /tmp/sample-repo

  test_clone_with_prior_checkout:
    <<: *docker_base_small
    parameters:
      repo_coordinates: {type: string}
      lfs: {type: boolean}
      submodules: {type: boolean}
    steps:
      - checkout
      - bats/install
      - test_clone_git_repo:
          debug: false
          repo_url_template: "https://github.com/rynkowsg/test-clone-repo-%s.git"
          repo_coordinates: << parameters.repo_coordinates >>
          lfs: << parameters.lfs >>
          submodules: << parameters.submodules >>
          dest_dir: /tmp/sample-repo

  test_clone_shallow:
    <<: *docker_base_small
    parameters:
      repo_coordinates: {type: string}
      depth: {type: integer}
    steps:
      - bats/install
      - test_clone_git_repo:
          debug: false
          repo_url_template: "https://github.com/rynkowsg/test-clone-repo-%s.git"
          repo_coordinates: << parameters.repo_coordinates >>
          depth: << parameters.depth >>

workflows:
  test-deploy:
    jobs:
      - test_clone_without_prior_checkout:
          name: "test_clone-wo/co-<< matrix.repo_coordinates >>-C:<< matrix.context >>-L:<< matrix.lfs >>-S:<< matrix.submodules >>"
          context:
            - gr/test-clone-github-https
            - << matrix.context >>
          matrix:
            parameters:
              repo_coordinates:
                - "l0|master-lfs||f731330"
                - "l0|master||7a87a29"
                - "l1|master-lfs||fcb0be3"
                - "l1|master||5345a62"
                - "l2|master-lfs||59550f0"
                - "l2|master||da342f2"
              context: [gr/empty, gr/test-clone]
              lfs: [true, false]
              submodules: [true, false]
          filters: *filters

      - test_clone_with_prior_checkout:
          name: "test_clone-w/co-<< matrix.repo_coordinates >>-C:<< matrix.context >>-L:<< matrix.lfs >>-S:<< matrix.submodules >>"
          context:
            - gr/test-clone-github-https
            - << matrix.context >>
          matrix:
            parameters:
              repo_coordinates:
                - "l0|master-lfs||f731330"
                - "l0|master||7a87a29"
                - "l1|master-lfs||fcb0be3"
                - "l1|master||5345a62"
                - "l2|master-lfs||59550f0"
                - "l2|master||da342f2"
              context: [gr/empty, gr/test-clone]
              lfs: [true, false]
              submodules: [true, false]
          filters: *filters

      - test_clone_shallow:
          name: "test_clone_shadow-<< matrix.repo_coordinates >>-D:<< matrix.depth >>"
          context: [gr/test-clone-github-https]
          matrix:
            parameters:
              repo_coordinates:
                - "l2|master||da342f2"
                - "l2||0.1.0|da342f2"
              depth: [1, -1]
          filters: *filters

      - orb-tools/pack:
          requires:
            - test_clone_without_prior_checkout
            - test_clone_with_prior_checkout
            - test_clone_shallow
          filters: *filters

      - orb-tools/publish:
          name: publish-dev
          orb_name: rynkowsg/checkout
          vcs_type: << pipeline.project.type >>
          pub_type: dev
          requires:
            - orb-tools/pack
          context: circleci/orb-publishing-context
          filters: *filters

      - orb-tools/publish:
          name: publish-prod
          orb_name: rynkowsg/checkout
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - publish-dev
          context: circleci/orb-publishing-context
          filters: *release-filters
