version: 2.1
orbs:
  # https://circleci.com/developer/orbs/orb/circleci/android
  # https://github.com/circleci-public/android-orb/releases
  # No need to update it since this particular version was used when detected the problem.
  # I don't want to reconstruct manually environment when the issue was detected.
  android: circleci/android@2.5.0 # Don't update it.
  # changelog: https://github.com/CircleCI-Public/BATS-orb/releases
  bats: circleci/bats@1.1.0
  # orb in this repo
  checkout: {}
  # orb info: https://circleci.com/developer/orbs/orb/circleci/orb-tools
  # changelog: https://github.com/CircleCI-Public/orb-tools-orb/releases
  orb-tools: circleci/orb-tools@12.3.1
  # orb info: https://circleci.com/developer/orbs/orb/rynkowsg/rynkowsg
  rynkowsg: rynkowsg/rynkowsg@0.6.0

commands:
  test_clone_git_repo:
    parameters:
      # parameters copied from clone_git_repo
      bash_path:
        type: string
        default: ""
        description: |
          The command requires at least Bash 4.
          If the default is lower, it needs to be installed before the command.
          If value not provided, the default bash is used.
      debug:
        type: boolean
        default: false
        description: |
          When true, debug command logging is enabled
      depth:
        type: integer
        default: -1
        description: |
          Specifies the clone depth, indicating the number of recent commits to include.
          Default: -1 (fetches all commits).
      depth_for_submodules:
        type: integer
        default: -1
        description: |
          Specifies the clone depth for submodules, indicating the number of recent commits to include.
          Default: -1 (fetches all commits).
      dest_dir:
        type: string
        default: ""
        description: |
          Destination directory for the repository.
          Defaults to DEST_DIR, then CIRCLE_WORKING_DIRECTORY, or current directory if unset.
      github_token:
        type: string
        default: ""
        description: |
          GitHub token. It can help to surpass connection quotas per machine.
      name_displayed:
        type: string
        default: "checkout/checkout"
        description: |
          The display name for the command.
        #repo_branch:
        #  type: string
        #  default: ""
        #  description: |
        #    Specifies the branch to checkout.
        #    Defaults to REPO_BRANCH, then CIRCLE_BRANCH if unset.
        #repo_sha1:
        #  type: string
        #  default: ""
        #  description: |
        #    Specifies the commit SHA1 to checkout.
        #    Defaults to REPO_SHA1, then CIRCLE_SHA1 if unset.
        #repo_tag:
        #  type: string
        #  default: ""
        #  description: |
        #    Specifies the tag to checkout.
        #    Defaults to REPO_TAG, then CIRCLE_TAG if unset.
        #repo_url:
        #  type: string
        #  default: ""
        #  description: |
        #    Specifies the repository URL.
        #    Defaults to REPO_URL, then CIRCLE_REPOSITORY_URL if unset.
      with_lfs:
        type: boolean
        default: false
        description: |
          Enables cloning with Git Large File Storage (LFS) support.
      with_submodules:
        type: boolean
        default: false
        description: |
          Enables cloning of submodules.
      # parameters specific only to test_clone_git_repo:
      repo_coordinates:
        type: string
        description: "Replacement for commented above"
      repo_url_template:
        type: string
        description: "Repo URL used with one string value for repo name."
        default: "https://github.com/rynkowsg/rynkowsg-orb-sample-repo-%s.git"
    steps:
      - run:
          name: Extract repo details
          command: |
            set -x
            IFS='|' read -r repo_name repo_branch repo_tag repo_sha1 < <(echo "<<parameters.repo_coordinates>>")
            echo "export REPO_URL=\"$(printf "<<parameters.repo_url_template>>" "${repo_name}")\"" >> $BASH_ENV
            echo "export REPO_BRANCH=$repo_branch" >> $BASH_ENV
            echo "export REPO_TAG=$repo_tag" >> $BASH_ENV
            echo "export REPO_SHA1=$repo_sha1" >> $BASH_ENV
      - checkout/checkout:
          debug: <<parameters.debug>>
          depth: <<parameters.depth>>
          depth_for_submodules: <<parameters.depth_for_submodules>>
          dest_dir: <<parameters.dest_dir>>
          name_displayed: <<parameters.name_displayed>>
          with_lfs: <<parameters.with_lfs>>
          with_submodules: <<parameters.with_submodules>>
      - run:
          name: "Run tests"
          environment:
            LFS_ENABLED: <<parameters.with_lfs>>
            SUBMODULES_ENABLED: <<parameters.with_submodules>>
            PARAM_DEST_DIR: <<parameters.dest_dir>>
          command: |
            # the DEST_DIR logic here maches logic from the checkout bash impl
            DEST_DIR=${PARAM_DEST_DIR:-${DEST_DIR:-${CIRCLE_WORKING_DIRECTORY:-.}}}
            eval DEST_DIR="${DEST_DIR}"
            ${DEST_DIR}/@bin/test.bash

# Use this tag to ensure test jobs always run,
# even though the downstream publish job will only run on release tags.
filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  test_clone_double:
    parameters:
      debug: {type: boolean, default: false}
      executor: {type: executor}
    executor: <<parameters.executor>>
    steps:
      - checkout/checkout:
          debug: <<parameters.debug>>
          repo_url: "https://github.com/rynkowsg/test-clone-repo-l2.git"
          repo_branch: master
          repo_sha1: da342f2
      - checkout/checkout:
          debug: <<parameters.debug>>
          repo_url: "https://github.com/rynkowsg/test-clone-repo-l2.git"
          repo_branch: master-lfs
          repo_sha1: 59550f0

  test_clone_double_shallow:
    parameters:
      debug: {type: boolean, default: false}
      executor: {type: executor}
    executor: <<parameters.executor>>
    steps:
      - checkout/checkout:
          debug: <<parameters.debug>>
          repo_url: "https://github.com/rynkowsg/test-clone-repo-l2.git"
          repo_branch: master
          repo_sha1: da342f2
          depth: 1
      - checkout/checkout:
          debug: <<parameters.debug>>
          repo_url: "https://github.com/rynkowsg/test-clone-repo-l2.git"
          repo_branch: master-lfs
          repo_sha1: 59550f0
          depth: 1

  test_clone_simple:
    parameters:
      debug: {type: boolean, default: false}
      executor: {type: string}
    executor: <<parameters.executor>>
    steps:
      - when:
          condition: {not: {equal: ["<<parameters.executor>>", "rynkowsg/macos"]}}
          steps:
            - checkout/checkout:
                debug: <<parameters.debug>>
      - when:
          condition: {equal: ["<<parameters.executor>>", "rynkowsg/macos"]}
          steps:
            - rynkowsg/macos_install_bash
            - checkout/checkout:
                bash_path: /opt/homebrew/bin/bash
                debug: <<parameters.debug>>

  test_clone_shallow:
    parameters:
      debug: {type: boolean, default: false}
      repo_coordinates: {type: string}
      depth: {type: integer}
    executor: rynkowsg/docker_x86_cimg_base
    steps:
      - bats/install
      - test_clone_git_repo:
          debug: <<parameters.debug>>
          repo_url_template: "https://github.com/rynkowsg/test-clone-repo-%s.git"
          repo_coordinates: <<parameters.repo_coordinates>>
          depth: <<parameters.depth>>

  test_clone_full:
    parameters:
      debug: {type: boolean, default: false}
      repo_coordinates: {type: string}
      with_lfs: {type: boolean}
      with_prior_builtin_checkout: {type: boolean, default: false}
      with_submodules: {type: boolean}
    executor: rynkowsg/docker_x86_cimg_base
    steps:
      - when:
          condition: <<parameters.with_prior_builtin_checkout>>
          steps:
            - checkout
      - bats/install
      - test_clone_git_repo:
          debug: <<parameters.debug>>
          dest_dir: /tmp/sample-repo
          repo_coordinates: <<parameters.repo_coordinates>>
          repo_url_template: "https://github.com/rynkowsg/test-clone-repo-%s.git"
          with_lfs: <<parameters.with_lfs>>
          with_submodules: <<parameters.with_submodules>>

  test_clone_with_cd_overridden:
    parameters:
      debug: {type: boolean, default: false}
    executor: {name: android/android-machine, resource-class: medium, tag: 2023.10.1}
    steps:
      - run:
          name: Preview the file bashrc
          command: |
            set -x
            ls -al ~
            [ -f ~/.bashrc ] && cat ~/.bashrc
            [ -f ~/.circlerc ] && cat ~/.circlerc
            declare -f cd
            exit 0
      - bats/install
      - test_clone_git_repo:
          debug: <<parameters.debug>>
          dest_dir: /tmp/sample-repo
          repo_coordinates: "l0|master-lfs||f731330"
          repo_url_template: "https://github.com/rynkowsg/test-clone-repo-%s.git"
          with_lfs: true
          with_submodules: true

workflows:
  test-deploy:
    jobs:
      - test_clone_double:
          name: test_clone_double, E:<<matrix.executor>>
          matrix:
            parameters:
              executor:
                - rynkowsg/docker_x86_cimg_base
          debug: false
          filters: *filters

      - test_clone_double_shallow:
          name: test_clone_double_shallow, E:<<matrix.executor>>
          matrix:
            parameters:
              executor:
                - rynkowsg/docker_x86_cimg_base
          debug: false
          filters: *filters

      # test running the command on different systems
      - test_clone_simple:
          name: test_clone_simple, E:<<matrix.executor>>
          matrix:
            parameters:
              executor:
                - rynkowsg/docker_arm_cimg_base
                - rynkowsg/docker_x86_cimg_base
                - rynkowsg/machine_arm_ubuntu2204
                - rynkowsg/machine_x86_android
                - rynkowsg/machine_x86_ubuntu2204
                - rynkowsg/macos
          debug: false
          filters: *filters

      # test making shallow clones
      - test_clone_shallow:
          name: "test_clone_shadow; <<matrix.repo_coordinates>>, D:<<matrix.depth>>"
          matrix:
            parameters:
              depth: [1, 10]
              repo_coordinates:
                - "l2|master||da342f2"
                - "l2||0.1.0|da342f2"
                # master is at da342f2. master-lfs is ahead of da342f2.
                # by setting master-lfs with da342f2 we check whether clone with depth=1 works correctly
                - "l2|master-lfs||da342f2"
          context: [gr/test-clone-github-https]
          debug: false
          filters: *filters

      # test combination of authentication, lfs and submodules for public repository
      - test_clone_full:
          name: test_clone_full, <<matrix.repo_coordinates>>, PC:<<matrix.with_prior_builtin_checkout>>, <<matrix.context>>, L:<<matrix.with_lfs>>, S:<<matrix.with_submodules>>
          context:
            - gr/test-clone-github-https
            - <<matrix.context>>
          debug: false
          matrix:
            parameters:
              repo_coordinates:
                - "l0|master-lfs||f731330"
                - "l0|master||7a87a29"
                #- "l1|master-lfs||fcb0be3"
                #- "l1|master||5345a62"
                #- "l2|master-lfs||59550f0"
                #- "l2|master||da342f2"
              context: [gr/empty, gr/test-clone-ssh-identity-b64]
              with_lfs: [true, false]
              with_prior_builtin_checkout: [true, false]
              with_submodules: [true, false]
          filters: *filters

      - test_clone_with_cd_overridden:
          debug: true
          filters: *filters

      - orb-tools/pack:
          requires:
            - test_clone_double
            - test_clone_double_shallow
            - test_clone_full
            - test_clone_shallow
            - test_clone_simple
            - test_clone_with_cd_overridden
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters

      - orb-tools/publish:
          name: publish-dev
          requires:
            - orb-tools/pack
          context: circleci/orb-publishing-context
          executor: {name: orb-tools/default, resource_class: small}
          filters: *filters
          orb_name: rynkowsg/checkout
          pub_type: dev
          vcs_type: <<pipeline.project.type>>

      - orb-tools/publish:
          name: publish-prod
          requires:
            - publish-dev
          context: circleci/orb-publishing-context
          executor: {name: orb-tools/default, resource_class: small}
          filters: *release-filters
          orb_name: rynkowsg/checkout
          pub_type: production
          vcs_type: <<pipeline.project.type>>
